# Generated by Django 6.0.7 on 2026-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('address', models.TextField()),
                ('role', models.CharField(max_length=150)),
            ],
        ),
    ]
